import { useEffect, useState, type FormEvent } from "react"
import { useNavigate, useParams } from "react-router-dom"
import { ArrowLeft, BriefcaseBusiness } from "lucide-react"
import { useTranslation } from "react-i18next"

import { Page } from "@/components/Page"
import { FormSection } from "@/components/FormSection"
import { FormInput } from "@/components/FormInput"
import { AppButton } from "@/components/AppButton"
import { FormActions } from "@/components/FormActions"
import { Switch } from "@/components/ui/switch"
import { ConfirmDialog } from "@/components/ui/confirm-dialog"
import { useResource, useResourceMutation } from "@/lib/query"
import { save, destroy } from "@/lib/resource"
import { ApiError, type JobTitleRow } from "@/lib/api"
import { useAuthStore } from "@/store/auth-store"

const empty = {
  name: "",
  description: "",
  isActive: true,
}

type FormState = typeof empty

export default function JobTitleFormPage() {
  const navigate = useNavigate()
  const { t } = useTranslation()
  const { id } = useParams()
  const editing = id != null
  const jobTitleId = id ? Number(id) : null
  const invalidId = editing && (jobTitleId == null || Number.isNaN(jobTitleId))
  const canDelete = useAuthStore((s) => s.hasPermission("jobtitles.delete"))

  const [form, setForm] = useState<FormState>(empty)
  const [dirty, setDirty] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [code, setCode] = useState<string>("")

  const { data: existing, isLoading, isError } = useResource<JobTitleRow>(
    `jobtitles/${jobTitleId}`,
    {},
    { enabled: editing && !invalidId },
  )

  useEffect(() => {
    if (invalidId || isError) navigate("/job-titles", { replace: true })
  }, [invalidId, isError, navigate])

  useEffect(() => {
    if (!existing) return
    setForm({
      name: existing.name,
      description: existing.description ?? "",
      isActive: existing.isActive,
    })
    setCode(existing.code)
    setDirty(false)
  }, [existing])

  const mutation = useResourceMutation<JobTitleRow, FormState>(
    (data) =>
      save<JobTitleRow>("jobtitles", jobTitleId, {
        name: data.name.trim(),
        description: data.description.trim() || null,
        isActive: data.isActive,
      }),
    ["jobtitles"],
  )

  const deleteMutation = useResourceMutation<void, number>(
    (jid) => destroy("jobtitles", jid),
    ["jobtitles"],
  )

  function update<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }))
    setDirty(true)
    setErrors((prev) => {
      if (!prev[key]) return prev
      const next = { ...prev }
      delete next[key]
      return next
    })
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setErrors({})
    try {
      await mutation.mutateAsync(form)
      navigate("/job-titles")
    } catch (err) {
      if (err instanceof ApiError) setErrors(err.fieldErrors)
    }
  }

  function requestLeave() {
    if (dirty) setConfirmOpen(true)
    else navigate("/job-titles")
  }

  async function handleDelete() {
    if (jobTitleId == null) return
    await deleteMutation.mutateAsync(jobTitleId)
    setDeleteOpen(false)
    navigate("/job-titles")
  }

  return (
    <Page
      title={editing ? t("jobTitleForm.editTitle") : t("jobTitleForm.newTitle")}
      icon={BriefcaseBusiness}
      description={editing ? t("jobTitleForm.editDescription") : t("jobTitleForm.newDescription")}
      breadcrumbs={[
        { label: t("nav.dashboard"), to: "/dashboard" },
        { label: t("nav.jobTitles"), to: "/job-titles" },
        { label: editing ? t("jobTitleForm.editTitle") : t("jobTitleForm.newTitle") },
      ]}
      loading={editing && isLoading}
      actions={
        <AppButton variant="outline" icon={ArrowLeft} onClick={requestLeave}>
          {t("common.back")}
        </AppButton>
      }
    >
      <form onSubmit={handleSubmit} className="flex max-w-2xl flex-col gap-4">
        <FormSection title={t("jobTitleForm.details")} icon={BriefcaseBusiness}>
          <div className="grid gap-5 sm:grid-cols-2">
            <FormInput
              id="name"
              label={t("jobTitleForm.name")}
              required
              value={form.name}
              onValueChange={(v) => update("name", (v as string) ?? "")}
              error={errors.name}
            />
            {editing && (
              <FormInput
                id="code"
                label={t("jobTitleForm.code")}
                value={code}
                onValueChange={() => undefined}
                readOnly
                hint={t("common.autoGenerated")}
              />
            )}
          </div>

          <FormInput
            id="description"
            type="textarea"
            rows={3}
            label={t("jobTitleForm.description")}
            value={form.description}
            onValueChange={(v) => update("description", (v as string) ?? "")}
            error={errors.description}
          />

          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium">{t("jobTitleForm.active")}</p>
              <p className="text-xs text-muted-foreground">{t("jobTitleForm.activeHint")}</p>
            </div>
            <Switch
              checked={form.isActive}
              onCheckedChange={(checked) => update("isActive", checked)}
            />
          </div>
        </FormSection>

        <FormActions
          editing={editing}
          onCancel={requestLeave}
          saving={mutation.isPending}
          showDelete={editing && canDelete}
          onDelete={() => setDeleteOpen(true)}
        />
      </form>

      <ConfirmDialog
        open={confirmOpen}
        title={t("common.discardTitle")}
        description={t("common.discardDescription")}
        confirmLabel={t("common.discard")}
        cancelLabel={t("common.cancel")}
        destructive
        onConfirm={() => {
          setConfirmOpen(false)
          navigate("/job-titles")
        }}
        onCancel={() => setConfirmOpen(false)}
      />

      <ConfirmDialog
        open={deleteOpen}
        title={t("jobTitleForm.deleteTitle")}
        description={t("jobTitleForm.deleteDescription")}
        confirmLabel={t("common.delete")}
        cancelLabel={t("common.cancel")}
        destructive
        onConfirm={handleDelete}
        onCancel={() => setDeleteOpen(false)}
      />
    </Page>
  )
}
