using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Onboardly.Server.Authorization;
using Onboardly.Server.Models;

namespace Onboardly.Server.Infrastructure;

// Captures Create/Update/Delete on domain entities into AuditLog rows, tagged
// with the active tenant, user and request metadata. Runs in the same
// transaction as the change; keys generated by the store are resolved after
// SaveChanges so inserts get a real EntityId.
public class AuditInterceptor : SaveChangesInterceptor
{
    // Never write these property values into the audit trail.
    private static readonly HashSet<string> Redacted = new(StringComparer.Ordinal)
    {
        nameof(User.PasswordHash),
    };

    private readonly ITenantContext _tenant;
    private readonly IHttpContextAccessor _http;
    private List<PendingAudit>? _pending;

    public AuditInterceptor(ITenantContext tenant, IHttpContextAccessor http)
    {
        _tenant = tenant;
        _http = http;
    }

    public override InterceptionResult<int> SavingChanges(
        DbContextEventData eventData, InterceptionResult<int> result)
    {
        _pending = Capture(eventData.Context);
        return base.SavingChanges(eventData, result);
    }

    public override ValueTask<InterceptionResult<int>> SavingChangesAsync(
        DbContextEventData eventData, InterceptionResult<int> result, CancellationToken ct = default)
    {
        _pending = Capture(eventData.Context);
        return base.SavingChangesAsync(eventData, result, ct);
    }

    public override int SavedChanges(SaveChangesCompletedEventData eventData, int result)
    {
        Flush(eventData.Context);
        return base.SavedChanges(eventData, result);
    }

    public override async ValueTask<int> SavedChangesAsync(
        SaveChangesCompletedEventData eventData, int result, CancellationToken ct = default)
    {
        await FlushAsync(eventData.Context, ct);
        return await base.SavedChangesAsync(eventData, result, ct);
    }

    private List<PendingAudit>? Capture(DbContext? context)
    {
        if (context is null)
            return null;

        var pending = new List<PendingAudit>();
        foreach (var entry in context.ChangeTracker.Entries())
        {
            if (!ShouldAudit(entry))
                continue;

            // A soft delete is stored as an UPDATE (IsDeleted false -> true) but
            // is semantically a deletion, so record it as such with the pre-delete
            // snapshot for the audit trail.
            var softDeleted = IsSoftDelete(entry);

            var (oldValues, newValues) = entry.State switch
            {
                EntityState.Added => (null, Snapshot(entry, current: true)),
                EntityState.Deleted => (Snapshot(entry, current: false), (Dictionary<string, object?>?)null),
                EntityState.Modified when softDeleted => (Snapshot(entry, current: false), (Dictionary<string, object?>?)null),
                EntityState.Modified => (
                    Snapshot(entry, current: false, changedOnly: true),
                    Snapshot(entry, current: true, changedOnly: true)),
                _ => (null, (Dictionary<string, object?>?)null),
            };

            pending.Add(new PendingAudit(
                entry,
                softDeleted ? "Delete" : ActionFor(entry.State),
                entry.Metadata.ClrType.Name,
                oldValues,
                newValues));
        }

        return pending.Count > 0 ? pending : null;
    }

    private void Flush(DbContext? context)
    {
        var rows = Drain(context);
        if (rows is null)
            return;
        context!.Set<AuditLog>().AddRange(rows);
        context.SaveChanges();
    }

    private async Task FlushAsync(DbContext? context, CancellationToken ct)
    {
        var rows = Drain(context);
        if (rows is null)
            return;
        await context!.Set<AuditLog>().AddRangeAsync(rows, ct);
        await context.SaveChangesAsync(ct);
    }

    // Materialize pending captures into AuditLog rows. Clears _pending first so
    // the nested SaveChanges (which persists these rows) doesn't recurse.
    private List<AuditLog>? Drain(DbContext? context)
    {
        var pending = _pending;
        _pending = null;
        if (context is null || pending is null)
            return null;

        var ip = _http.HttpContext?.Connection.RemoteIpAddress?.ToString();
        var userAgent = _http.HttpContext?.Request.Headers.UserAgent.ToString();
        var timestamp = DateTime.UtcNow;

        return pending.Select(p => new AuditLog
        {
            OrganizationId = _tenant.OrganizationId,
            UserId = _tenant.UserId,
            Action = p.Action,
            EntityType = p.EntityType,
            EntityId = KeyOf(p.Entry),
            OldValues = Serialize(p.OldValues),
            NewValues = Serialize(p.NewValues),
            Timestamp = timestamp,
            IpAddress = ip,
            UserAgent = string.IsNullOrEmpty(userAgent) ? null : userAgent,
        }).ToList();
    }

    private static bool ShouldAudit(EntityEntry entry)
    {
        if (entry.State is not (EntityState.Added or EntityState.Modified or EntityState.Deleted))
            return false;
        if (entry.Entity is AuditLog)
            return false;
        // Skip join/property-bag rows (e.g. role_user); explicit auditing can be
        // added for those relationships if needed.
        if (entry.Metadata.IsPropertyBag)
            return false;
        return entry.Metadata.ClrType.Namespace == typeof(User).Namespace;
    }

    // True when a modification flips a soft-deletable entity's IsDeleted to true.
    private static bool IsSoftDelete(EntityEntry entry)
    {
        if (entry.State != EntityState.Modified || entry.Entity is not ISoftDeletable)
            return false;
        var flag = entry.Property(nameof(ISoftDeletable.IsDeleted));
        return flag.IsModified
            && flag.OriginalValue is false
            && flag.CurrentValue is true;
    }

    private static Dictionary<string, object?> Snapshot(
        EntityEntry entry, bool current, bool changedOnly = false)
    {
        var values = new Dictionary<string, object?>();
        foreach (var prop in entry.Properties)
        {
            if (Redacted.Contains(prop.Metadata.Name))
                continue;
            if (changedOnly && !prop.IsModified)
                continue;
            values[prop.Metadata.Name] = current ? prop.CurrentValue : prop.OriginalValue;
        }
        return values;
    }

    private static string KeyOf(EntityEntry entry) =>
        string.Join(",", entry.Properties
            .Where(p => p.Metadata.IsPrimaryKey())
            .Select(p => p.CurrentValue?.ToString()));

    private static string ActionFor(EntityState state) => state switch
    {
        EntityState.Added => "Create",
        EntityState.Modified => "Update",
        EntityState.Deleted => "Delete",
        _ => state.ToString(),
    };

    private static string? Serialize(Dictionary<string, object?>? values) =>
        values is null || values.Count == 0 ? null : JsonSerializer.Serialize(values);

    private sealed record PendingAudit(
        EntityEntry Entry,
        string Action,
        string EntityType,
        Dictionary<string, object?>? OldValues,
        Dictionary<string, object?>? NewValues);
}
