namespace Onboardly.Server.Models;

// Daily attendance status. A deliberately broad lookup so the same record shape
// serves office, remote and field workforces. Shift/holiday/leave modules will
// later drive some of these automatically.
public enum AttendanceStatus
{
    Present = 0,
    Absent = 1,
    Late = 2,
    HalfDay = 3,
    Leave = 4,
    Holiday = 5,
    Weekend = 6,
    WorkFromHome = 7,
    OnDuty = 8,
    // Checked in but never checked out past office close — awaiting HR review.
    MissingPunch = 9,
}

// Days of the week an organization operates on. A [Flags] bitmask so a schedule
// is stored in a single column and combined freely (5-day, 6-day, alternate).
[Flags]
public enum WorkDays
{
    None = 0,
    Monday = 1,
    Tuesday = 2,
    Wednesday = 4,
    Thursday = 8,
    Friday = 16,
    Saturday = 32,
    Sunday = 64,
    Weekdays = Monday | Tuesday | Wednesday | Thursday | Friday,
}

// Converts the WorkDays bitmask to/from a frontend-friendly list of day names
// (e.g. ["Monday","Tuesday"]) so the API never exposes the raw bitmask.
public static class WorkDaysExtensions
{
    private static readonly (WorkDays Flag, string Name)[] Map =
    {
        (WorkDays.Monday, "Monday"),
        (WorkDays.Tuesday, "Tuesday"),
        (WorkDays.Wednesday, "Wednesday"),
        (WorkDays.Thursday, "Thursday"),
        (WorkDays.Friday, "Friday"),
        (WorkDays.Saturday, "Saturday"),
        (WorkDays.Sunday, "Sunday"),
    };

    public static string[] ToNames(this WorkDays days) =>
        Map.Where(d => days.HasFlag(d.Flag)).Select(d => d.Name).ToArray();

    public static WorkDays FromNames(IEnumerable<string>? names)
    {
        if (names is null)
            return WorkDays.None;
        var set = names.Select(n => n.Trim()).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var result = WorkDays.None;
        foreach (var (flag, name) in Map)
            if (set.Contains(name))
                result |= flag;
        return result;
    }
}

// A single punch on a day. Break events bracket unpaid time; check in/out bound
// the working window.
public enum AttendanceEventType
{
    CheckIn = 0,
    CheckOut = 1,
    BreakStart = 2,
    BreakEnd = 3,
}

// Where a punch originated. Kept extensible so biometric/RFID/GPS/face capture
// devices can be added later without a schema change.
public enum AttendanceSource
{
    Web = 0,
    Manual = 1,
    Biometric = 2,
    Rfid = 3,
    Gps = 4,
    FaceRecognition = 5,
    Import = 6,
    // Generated by the server (e.g. the auto-checkout sweep at office close).
    System = 7,
}

// State of an employee-raised attendance correction request.
public enum CorrectionStatus
{
    Pending = 0,
    Approved = 1,
    Rejected = 2,
}
